{% set name = "asyncinotify" %}
{% set version = "4.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 95840eec6804797f9e8ee6d65a9d2a1159e77c5395a468dcfa4f44338ed1f8b6

build:
  number: 0
  skip: true  # [not linux or py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - flit-core >=3.2,<4
  run:
    - python

test:
  imports:
    - asyncinotify

about:
  home: https://gitlab.com/Taywee/asyncinotify
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: An async python inotify package
  description: |
    An async python inotify package. Kept as simple and easy-to-understand
    as possible, while still being flexible and powerful. This is built on
    no external dependencies, and works through ctypes in a very obvious
    fashion.
  doc_url: https://asyncinotify.readthedocs.io/
  dev_url: https://gitlab.com/Taywee/asyncinotify

extra:
  recipe-maintainers:
    - mareuter
