{% set name = "asyncinotify" %}
{% set version = "3.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d9938f01b8368d24e14ed5000a1c094391c7f6d543de142fd3425810409743a7

build:
  number: 0
  skip: true  # [not linux or py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - asyncinotify

about:
  home: https://gitlab.com/Taywee/asyncinotify
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An async python inotify package
  description: |
    An async python inotify package. Kept as simple and easy-to-understand
    as possible, while still being flexible and powerful. This is built on
    no external dependencies, and works through ctypes in a very obvious
    fashion.
  doc_url: https://asyncinotify.readthedocs.io/
  dev_url: https://gitlab.com/Taywee/asyncinotify

extra:
  recipe-maintainers:
    - mareuter
