{% set name = "asyncinotify" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dac1d75e16a4919c6eab84a90ff51218db622c5524a84a5c501a0b62ea7ec7ea

build:
  number: 0
  skip: true  # [not linux or py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - flit-core >=3.2,<4
  run:
    - python

test:
  imports:
    - asyncinotify

about:
  home: https://github.com/ProCern/asyncinotify
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: An async python inotify package
  description: |
    An async python inotify package. Kept as simple and easy-to-understand
    as possible, while still being flexible and powerful. This is built on
    no external dependencies, and works through ctypes in a very obvious
    fashion.
  doc_url: https://asyncinotify.readthedocs.io/
  dev_url: https://github.com/ProCern/asyncinotify

extra:
  recipe-maintainers:
    - mareuter
